embed_assets: on

javascripts:
  common:
    - public/javascripts/jquery-1.5.1.min.js
    - public/javascripts/modernizr-1.6.min.js
    - public/javascripts/underscore.js
    - public/javascripts/backbone.js
    - public/javascripts/application.js
    
stylesheets:
  common:
    - public/stylesheets/reset.css
    - public/stylesheets/application.css
  # workspace:
  #   - public/stylesheets/pages/workspace.css
  # empty:
  #   - public/stylesheets/pages/empty.css